### ISSUE TITLE
[CHESS] I hope this is not an undercover stockfissue

### ISSUE THREAD

**Issue by juanfresia** [FdelMazo/BobbyFissue#38]

**Comment by juanfresia** [comment]
d4

**Comment by FdelMazo** [comment]
d5

**Comment by juanfresia** [comment]
Bf4

**Comment by FdelMazo** [comment]
Nc6

**Comment by juanfresia** [comment]
Nf3

**Comment by FdelMazo** [comment]
e6

**Comment by juanfresia** [comment]
e3

**Comment by FdelMazo** [comment]
Qf6

**Comment by juanfresia** [comment]
Bd3

**Comment by FdelMazo** [comment]
Cada movimiento tengo mas miedo

**Comment by FdelMazo** [comment]
Ne7

**Comment by FdelMazo** [comment]
Nge7

**Comment by FdelMazo** [comment]
(TIL how to make unambiguous SAN moves)

**Comment by juanfresia** [comment]
Kbd2

**Comment by juanfresia** [comment]
Nbd2 🤦

**Comment by juanfresia** [comment]
Puede fallar, 🤦 no es SAN compatible 😆

**Comment by juanfresia** [comment]
Nbd2

**Comment by FdelMazo** [comment]
Nf5

**Comment by juanfresia** [comment]
O-O

**Comment by FdelMazo** [comment]
Bf4

**Comment by FdelMazo** [comment]
Bb4

**Comment by juanfresia** [comment]
c3

**Comment by FdelMazo** [comment]
Ba5

**Comment by juanfresia** [comment]
e4

**Comment by FdelMazo** [comment]
Nh4

**Comment by juanfresia** [comment]
Bg3

**Comment by FdelMazo** [comment]
dxe5

**Comment by FdelMazo** [comment]
dxe4

**Comment by juanfresia** [comment]
Nxe4

**Comment by FdelMazo** [comment]
Qg6

**Comment by juanfresia** [comment]
Nxh4

**Comment by FdelMazo** [comment]
Qh6

**Comment by juanfresia** [comment]
d5

**Comment by FdelMazo** [comment]
Ne7

**Comment by juanfresia** [comment]
Qa4+

**Comment by FdelMazo** [comment]
Nc6

**Comment by juanfresia** [comment]
dxc6

**Comment by FdelMazo** [comment]
b6

**Comment by juanfresia** [comment]
Qa3

**Comment by FdelMazo** [comment]
O-O

**Comment by juanfresia** [comment]
Regla poco intuitiva, pero el rey no puede "pasar" por una casilla atacada al enrocar

**Comment by FdelMazo** [comment]
No vi a la reina, que gilun

**Comment by FdelMazo** [comment]
e5

**Comment by juanfresia** [comment]
Feel you, las diagonales sin los colores de las casillas son muy confusas, cuesta el triple seguirlas

**Comment by FdelMazo** [comment]
Si, y despues tenes todo el tema de los tamaños de los casilleros, que cuando un rank no tiene piezas te queda como una tabla de markdown normal, y re cuesta darte cuenta que casilleros son.

Pense en hacer lo que hace [timburgan](https://github.com/timburgan/timburgan) y ponerle para que complete con cuadrados los casilleros vacios, pero no me cerro tanto la idea

**Comment by juanfresia** [comment]
Rfe1

**Comment by juanfresia** [comment]
Es medio un hack, sip. Y el paso siguiente es tener dos imagenes con cada pieza, una para cada fondo... pero con el margen que te deja github en la visualización se vería medio feo.

**Comment by FdelMazo** [comment]
Ojo, si logras hacer programaticamente pegar un png arriba del otro en el momento, suena re divertido de hacer

**Comment by FdelMazo** [comment]
Bg4

**Comment by juanfresia** [comment]
Uhhh, esa es muy buena. Quien necesita piezas de dos colores si se puede tener una e invertirle los colores programáticamente. 👀

**Comment by juanfresia** [comment]
Bb5

**Comment by FdelMazo** [comment]
O-O-O

**Comment by FdelMazo** [comment]
O-O-O

**Comment by juanfresia** [comment]
Revelación inutil del día: acabo de darme cuenta que BB8 es un movimiento válido, pero R2D2 no (por muuy poco)

**Comment by juanfresia** [comment]
b4

**Comment by FdelMazo** [comment]
f5

**Comment by juanfresia** [comment]
Nc5

**Comment by FdelMazo** [comment]
bxc5

**Comment by juanfresia** [comment]
Qxa5

**Comment by FdelMazo** [comment]
Rd5

**Comment by juanfresia** [comment]
Nxf5

**Comment by FdelMazo** [comment]
Qd2

**Comment by juanfresia** [comment]
Qxa7

**Comment by FdelMazo** [comment]
Kd8

**Comment by FdelMazo** [comment]
:clap:

**Comment by juanfresia** [comment]
Qa8#

**Comment by juanfresia** [comment]
Gran juego, me encantó el proyecto 👏 ❤️

**Comment by FdelMazo** [comment]
Gracias! Re divertido el partido! Siempre podes armar otro issue, o pinguear en [lichess](https://lichess.org/@/fdelmazo)

**Comment by juanfresia** [comment]
Soy [irreconocible](https://lichess.org/@/creais) en lichess; pero juego seguido.
