### ISSUE TITLE
Rows with no piece should have an invisible picture

### ISSUE THREAD

**Issue by Ellipse0934** [FdelMazo/BobbyFissue#43]
TITLE
So that the board is rendered properly.
E.g.: 
![image](https://user-images.githubusercontent.com/7466364/149201919-ebb15e3b-1b58-4302-8cd3-33e5a0f8d0c2.png)

**Comment by FdelMazo** [comment]
Ty @Ellipse0934 !

This was fixed on 1d281be6331a72642562112db986d96a9341db74
