### ISSUE TITLE
Intended color assignment wrong.

### ISSUE THREAD

**Issue by scrapcode** [FdelMazo/BobbyFissue#44]
![image](https://user-images.githubusercontent.com/2568495/149206759-4b64e6f7-f9be-4872-99cb-3eea2ba59572.png)

Assigned black in "New game!" comment, but am actually white in game, and only controlling white pieces.

**Comment by FdelMazo** [comment]
There is nothing actually enforcing the player colors in the code. It's just an honor code. However, there is actually a bug on #42 , which is that the very first `e4` move was never commented.... I don't know from where did GH assume that move. Maybe a race condition?

Either way... the logs are long gone (the gh actions logs live for three months, and I totally forgot about this), so i'm gonna close this issue and hope it never comes up again (:
